
spring.config.import=optional:file:.env[.properties]
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/incident_db}
spring.data.mongodb.database=incident_db
google.oauth.client-id=${GOOGLE_CLIENT_ID:}
google.oauth.client-secret=${GOOGLE_CLIENT_SECRET:}
google.oauth.redirect-uri=${GOOGLE_REDIRECT_URI:}
flickr.api.key=${FLICKR_API_KEY:}
